name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Build package
        run: yarn build-ci

      - name: Publish
        run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN_AUTH }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN_AUTH }}
          NPM_TOKEN_AUTH: ${{ secrets.NPM_TOKEN_AUTH }}

